### ISSUE TITLE
Roadmap v1.1

### ISSUE THREAD

**Issue by dvbondoy** [dvbondoy/FlickOS#1]
**Design**

- [x] Add Catppuccin pastel theme and make default
- [x] Replace compton with picom

**Utilities**

- [x] Create desktop layout switcher application
- [x] Add rofi application launcher
- [ ] Add xlunch full-screen application launcher
- [ ] Create screen hot corner for expose application switcher
- [ ] Create on-boarding application

**Other**

- [ ] Create Wiki Documentation

**Comment by ghost** [comment]
Good Day, I'd like to contribute to your distribution, I'm the dev of Liya Linux ...

**Comment by dvbondoy** [comment]
> 

Hi Mohammad, sorry for the late reply. I was kind of busy in school for the past weeks. Yeah sure, it would be an honor to have you on board. Just found out about Liya, that's awesome.

**Comment by ghost** [comment]
@dvbondoy Sorry for the late reply, how can i contact you, like you do have any discord or telegram or any social?

**Comment by dvbondoy** [comment]
@mdhishamsayed my discord is dvbondoy#8868. you can also join the new subreddit at r/flickos.
